---
- name: Playbook to setup apps to a freshly installed ubuntu like laptop.
  hosts: all
  vars:
    - my_pkgs:
      - sublime-text
      - google-chrome-stable
  become: yes
  gather_facts: yes

  tasks:
      - name: Install GPG key for SublimeText
        apt_key:
          url: https://download.sublimetext.com/sublimehq-pub.gpg
          state: present

      - name: Install ansible
        apt:
            name: ansible
            state: present
      - name: Install snapd
        apt:
            name: snapd
            state: present
      - name: Install git
        apt:
            name: git
            state: present
      - name: Install vagrant
        apt:
            name: vagrant
            state: present
      - name: Install virtualbox
        apt:
            name: virtualbox
            state: present
      - name: Install vagrant
        apt:
            name: vagrant
            state: present
